### ISSUE TITLE
option to for .store location

### ISSUE THREAD

**Issue by jonathanong** [rstacruz/pnpm#1]
`node_modules/.store` makes sense by default, but there should be an option to put it wherever you want. my main thought is that i'd like to be able to `rm -rf node_modules`. if i don't want to `rm -rf` the store, then i would place it outside the `node_modules` directory.

**Comment by rstacruz** [comment]
i got better use cases for you:

1. keep the store in `~/.pnpm/node-4/store/` so that Babel doesn't take up 100MB for every project I have
2. since the 'global' store is prepended by the node major version, I can switch node versions and switch my compiled modules out by symlinks

this is actually the very reason I put pnpm together! I'm still contemplating on how to best do this, whether it's to symlink `~/.pnpm/node-4/store/lodash@4.0.0` -> `~/project/node_modules/.store/lodash@4.0.0` -> `~/project/node_modules/lodash`, or to skip the 2nd symlink entirely. Both have their pros and cons and I'm waiting to use pnpm for a while to get a feel of which would be the better approach. :+1:

**Comment by gtramontina** [comment]
Ooh! I like where this is going! :beers:

**Comment by jkroso** [comment]
@rstacruz what's the potential benefit of the extra symlink?

PS: the symlink approach is great in general since It saves tons of `rm -rf node_modules && npm i` though you will run into problems with babel and plugin-ish modules since people rely on the implementation details of npm occasionally. So expect to do a bit of [hackery](https://github.com/jkroso/packin/blob/708b27376b3e95c1f2f45676c555ce7aadd125b3/main.jl#L7).

**Comment by rstacruz** [comment]
jkroso: easier to account for what packages may (or may not) be in use. what if you stop using a dependency in one of your projects... how do we keep track that no project needs it anymore?

**Comment by rstacruz** [comment]
okay there's a super secret flag that lets you do this:

```sh
npm config set pnpm_store_path node_modules/.store  # <- default
```

**Comment by kevinverelst** [comment]
Setting this flag does not seem to work for me, the packages are still stored in node_modules/.store.
Ideas are welcome

**Comment by kevinverelst** [comment]
Nvm, the flag is renamed to store_path it seems

**Comment by zkochan** [comment]
hey, I documented the usage of a shared store: https://github.com/rstacruz/pnpm/blob/master/docs/recipes/shared-store.md

**Comment by kevinverelst** [comment]
Great! Thanks

**Comment by dandv** [comment]
The link to the [pnpm shared store](https://github.com/pnpm/pnpm/issues/214#issuecomment-450642008) is now dead. Pointing to that other issue for SEO.
