### ISSUE TITLE
Postinstall scripts seem to ignore file copying

### ISSUE THREAD

**Issue by dmitriz** [rstacruz/pnpm#188]
As part of my following package installation I have automated copying files into user's directory:
https://www.npmjs.com/package/min-webpack

This works with `npm i min-webpack`, however, when trying `pnpm i min-webpack`, the files do not get copied, thought the copying scripts still run as I see from the console message:

```sh
  min-webpack@1.0.10! $ node index.js                                       
  min-webpack@1.0.10  = Begin copying files                                 
  min-webpack@1.0.10   - Copying file or directory: demo                    
  min-webpack@1.0.10   - Copying file or directory: webpack.config.js       
  min-webpack@1.0.10  = End copying files                                   
```

Is there any way to have the files copied with `pnpm`?

**Comment by zkochan** [comment]
Seems like the file that you copy are pasted to `/node_modules/.tmp/`

**Comment by zkochan** [comment]
I see what is the problem. In your code you assume the package is installed into `node_modules/<package-name>/`. However, pnpm downloads the deps into a temp subfolder and runs the postinstall scripts in a subfolder, not on the `node_modules` level.

I am not sure this is something that should be fixed in pnpm.

Your package can search up for the directory that contains the package.json file and paste the files there. [This package can help](https://www.npmjs.com/package/read-pkg-up)

**Comment by zkochan** [comment]
We can't fix this with the current node_modules structure and I don't think it's worth copy/pasting the packages just to solve this issue
