### ISSUE TITLE
Recipe to use pnpm on Travis CI

### ISSUE THREAD

**Issue by julien-f** [rstacruz/pnpm#450]
Hey!

I'm wondering: is there a way to use pnpm on Travis CI?

I bet it would greatly improve the speed of the tests (especially if the store is cached) :)

[Travis CI recipe](https://yarnpkg.com/en/docs/install-ci#travis-tab).

**Comment by zkochan** [comment]
Hey,

We have to document it somewhere, but here's how you can do it:

```yaml
before_install:
  - npm install -g pnpm
install:
  - pnpm install
```

**Note:** The `npm install -g pnpm` part will be fast because we bundle all the dependencies on pnpm.

We actually use pnpm to install pnpm dependencies: https://github.com/rstacruz/pnpm/blob/master/.travis.yml

But currently it won't work with a cached store because of circular symlinks: [pnpm install doesn't get the job done when node_modules is cached by Travis CI](https://github.com/rstacruz/pnpm/issues/315)

But the good news is, it is fast enough without caching.

**Comment by julien-f** [comment]
Nice!

Thanks :)
