### ISSUE TITLE
binstubs of deep dependencies

### ISSUE THREAD

**Issue by rstacruz** [rstacruz/pnpm#58]
When you do this:

```
npm install node-sass
find node_modules/.bin
```

npm2 and pnpm will get you the `node-sass` binstub:

```
node_modules/.bin
node_modules/.bin/node-sass
```

but npm3, with its flat dependency tree model, gets you binstubs of deep dendencies:

```
node_modules/.bin
node_modules/.bin/har-validator
node_modules/.bin/mkdirp
node_modules/.bin/node-gyp
node_modules/.bin/node-sass
node_modules/.bin/nopt
node_modules/.bin/rimraf
node_modules/.bin/sassgraph
node_modules/.bin/semver
node_modules/.bin/sshpk-conv
node_modules/.bin/sshpk-sign
node_modules/.bin/sshpk-verify
node_modules/.bin/strip-indent
node_modules/.bin/uuid
node_modules/.bin/which
node_modules/.bin/window-size
```

I'm planning on **not** supporting npm3's model on this, and keeping pnpm / npm2's behavior. While it's possible to support this in pnpm, I personally don't see the benefit of npm3's model and would not introduce complexity that will not be useful.

Any objections? (cc @davej @misterbyrne @indexzero and others who may be lurking)

**Comment by rstacruz** [comment]
By the way: pnpm recently _sort of_ supported npm3's flat tree as of v0.12. The deep dependencies don't litter `node_modules` (like npm3), though; they're neatly tucked into `node_modules/.store/node_modules`.

**Comment by davej** [comment]
Yes, I agree, don't support it. I actually much prefer pnpm's way of doing flat(-ish) deps compared to npm3.

1. It makes for a neater `node_modules` folder. This becomes annoying for doing quick hacks and debugging, I actually made [a module to help with this](https://github.com/davej/john) but pnpm's approach is nicer again.

2. npm3 allows easy direct access to all nth-depth dependencies through the project root. For example, you can do `require('lodash')` without specifying it as a dependency in `package.json` and it will probably work because some deep dependency is using lodash. I think it's more desirable that this should fail.

**Comment by misterbyrne** [comment]
:+1: I'm not a fan of having sub-dependencies so prominent anyway.

**Comment by rstacruz** [comment]
Aye. Settled then!
